services:
    db:
        image: postgres:alpine3.20
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: java2projekt
        # ports:
        #      - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        
    backend:
        build: ./back-end-spring
        # ports:
        #     - "9090:9090"
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/java2projekt
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_JPA_HIBERNATE_DDL_AUTO: update

    frontend:
        build: ./front-end
        # ports:
        #     - "80:80"
        depends_on:
            - backend
        environment:
            API_URL: http://turbolaft.com:9090
    reverse-proxy:
        image: nginx:alpine
        container_name: reverse-proxy
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /home/artem/https:/etc/nginx/certs
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - backend

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/artem/programming/Docker
        